
#application.yml \u914D\u7F6E\u5982\u4E0B\uFF1A
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8082


mybatis:
  configuration:
    map-underscore-to-camel-case: true